#!/usr/bin/env zsh

# Unicode Character Definitions for TUI

# Box Drawing Characters (examples)
# Light
BOX_LIGHT_HORIZ="─"
BOX_LIGHT_VERT="│"
BOX_LIGHT_DOWN_RIGHT="┌"
BOX_LIGHT_DOWN_LEFT="┐"
BOX_LIGHT_UP_RIGHT="└"
BOX_LIGHT_UP_LEFT="┘"
BOX_LIGHT_VERT_RIGHT="├"
BOX_LIGHT_VERT_LEFT="┤"
BOX_LIGHT_DOWN_HORIZ="┬"
BOX_LIGHT_UP_HORIZ="┴"
BOX_LIGHT_VERT_HORIZ="┼"
# Heavy
BOX_HEAVY_HORIZ="━"
BOX_HEAVY_VERT="┃"
BOX_HEAVY_DOWN_RIGHT="┏"
BOX_HEAVY_DOWN_LEFT="┓"
BOX_HEAVY_UP_RIGHT="┗"
BOX_HEAVY_UP_LEFT="┛"
BOX_HEAVY_VERT_RIGHT="┣"
BOX_HEAVY_VERT_LEFT="┫"
BOX_HEAVY_DOWN_HORIZ="┳"
BOX_HEAVY_UP_HORIZ="┻"
BOX_HEAVY_VERT_HORIZ="╋"
# Double
BOX_DOUBLE_HORIZ="═"
BOX_DOUBLE_VERT="║"
BOX_DOUBLE_DOWN_RIGHT="╔"
BOX_DOUBLE_DOWN_LEFT="╗"
BOX_DOUBLE_UP_RIGHT="╚"
BOX_DOUBLE_UP_LEFT="╝"
BOX_DOUBLE_VERT_RIGHT="╠"
BOX_DOUBLE_VERT_LEFT="╣"
BOX_DOUBLE_DOWN_HORIZ="╦"
BOX_DOUBLE_UP_HORIZ="╩"
BOX_DOUBLE_VERT_HORIZ="╬"
# Rounded
BOX_ROUNDED_DOWN_RIGHT="╭"
BOX_ROUNDED_DOWN_LEFT="╮"
BOX_ROUNDED_UP_RIGHT="╰"
BOX_ROUNDED_UP_LEFT="╯"

# Shading Characters (Block Elements)
SHADE_LIGHT="░"   # 25%
SHADE_MEDIUM="▒"  # 50%
SHADE_DARK="▓"    # 75%
SHADE_SOLID="█"   # 100% (Full block)
SHADE_LOWER_HALF="▄"
SHADE_UPPER_HALF="▀"
SHADE_LEFT_HALF="▌"
SHADE_RIGHT_HALF="▐"


# Common Unicode Symbols
SYMBOL_SPADES="♠"
SYMBOL_HEARTS="♡" # Using outline heart, solid ♥ might not be on all fonts
SYMBOL_DIAMONDS="♢" # Using outline diamond, solid ♦ might not be on all fonts
SYMBOL_CLUBS="♣"
SYMBOL_CHECKMARK="✓"
SYMBOL_CROSS_MARK="✗" # Ballot X
SYMBOL_RIGHT_ARROW="→"
SYMBOL_LEFT_ARROW="←"
SYMBOL_UP_ARROW="↑"
SYMBOL_DOWN_ARROW="↓"
SYMBOL_BULLET="•"
SYMBOL_STAR_FILLED="★"
SYMBOL_STAR_OUTLINE="☆"
SYMBOL_ELLIPSIS="…"
SYMBOL_COPYRIGHT="©"
SYMBOL_REGISTERED="®"
SYMBOL_TRADEMARK="™"
SYMBOL_DEGREE="°"
SYMBOL_PILCROW="¶" # Paragraph sign

# Ensure file is sourceable and doesn't produce output on source
:
